version: 2
updates:
  - package-ecosystem: nuget
    directories:
      - /StructuredJson
      - /StructuredJson.Tests
      - /examples/StructuredJson.Example
      - /benchmarks/StructuredJson.Benchmarks
    schedule:
      interval: weekly
    target-branch: development
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: development
